app:
  name: "YourAppName"
  version: "1.0.0"

server:
  host: "localhost"
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "your_db_user"
  password: "your_db_password"
  name: "your_db_name"

logging:
  level: "info"
  file: "logs/app.log"

api:
  key: "your_api_key"
  secret: "your_api_secret"
